### ISSUE TITLE
Missing polygons on road

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#101]
There are missing polygons on the road with the changes introduced in https://github.com/supermedium/moonrider/pull/100 cc/ @cabanier 

![image](https://user-images.githubusercontent.com/39342/77687119-392a4500-6f5b-11ea-9711-3466c37db0a1.png)

**Comment by dmarcos** [comment]
I believe there was some cache issues. I clear my browser data on Quest and that fixed the issue.

**Comment by cabanier** [comment]
It looks like you didn't use the update moon rider which fixes that issue.

**Comment by dmarcos** [comment]
It was a problem with the browser cache. We busted it and it seems to be working now. I keep the issue open for a bit until we're 100% sure it's fixed.
