### ISSUE TITLE
Ergonomic Improvements

### ISSUE THREAD

**Issue by assassinmaster46** [supermedium/moonrider#102]
- Adding vibrations to simulate impact with successful cutting/punching.

- Option to adjust the angle of the fists/swords.  On oculus quest, they are bent forward by about 45 degrees, still enjoyable but would be nice to hold the swords straight upright.

**Comment by ngokevin** [comment]
i think we've fixed the angle of the swords, it was a bug.

we do have vibrations but it looks like oculus browser has removed haptics for now...you can try http://moonrider.xyz (HTTP version) might have it
