### ISSUE TITLE
Sabers not correctly aligned on Occulus Quest

### ISSUE THREAD

**Issue by gbcreation** [supermedium/moonrider#103]
From a few days, sabers are not correctly aligned with the controllers. They are not in the palms of your hands, but are oriented like the barrel of a gun. So they are slightly above the hand. It is similar to what is described in the issue : https://github.com/supermedium/moonrider/issues/98

I can also see strange clipping too as described in the first response of the OP of the same issue.

Occulus Quest Browser: 8.4.0.0.1.2066710656
Chromium version: 79.0.3945.126

**Comment by dmarcos** [comment]
Any difference if you access over http? http://moonrider.xyz

**Comment by ngokevin** [comment]
thanks for reporting! i've reverted recent changes for now

**Comment by dmarcos** [comment]
@cabanier We had to revert the WebXR support. It seems the controller reported pose is different between WebXR and WebVR. Maybe adding an offset here in the WebXR case:

https://github.com/supermedium/moonrider/blob/master/src/components/controller.js#L23

https://aframe.io/docs/1.0.0/components/oculus-touch-controls.html#value_orientationoffset

**Comment by cabanier** [comment]
I believe we investigated this and tracked it down to a change in three.js.
Do you want me to change it?

**Comment by dmarcos** [comment]
A-Frame has its own way of tracking controllers pose. Not sure if it's THREE related. You're more than welcome to recommit the old PR with a fix for the controllers orientation. It would be awesome.

**Comment by gbcreation** [comment]
Thank you very much for the investigation. I confirm sabers are correctly oriented now.

**Comment by cabanier** [comment]
@dmarcos I'm trying to fix this issue but I'm running into cors issues so I can't get the game started.
Do you know how I can get unblocked?

**Comment by dmarcos** [comment]
@cabanier Try clearing your browser cache. It should work.

**Comment by cabanier** [comment]
> @cabanier Try clearing your browser cache. It should work. Are you testing on `localhost`?

No, I spun up a server. I will try to see if I can get `localhost` to work. (I ran into node issues in the past)

**Comment by cabanier** [comment]
@dmarcos I got localhost to work and tried to change the default orientation of the controller in `controller.js`. However, it doesn't seem to make a difference and the hands are always in the same position.

The rotation comes [this line](https://github.com/aframevr/aframe/blob/9cf4677e4be00d561ce204cd5d35b732a742b956/src/components/oculus-touch-controls.js#L139) in aframe.

**Comment by dmarcos** [comment]
You should be able to override the default value in https://github.com/supermedium/moonrider/blob/master/src/components/controller.js#L23

**Comment by cabanier** [comment]
Maybe it is fixed. 
I'll put up a PR.

**Comment by dmarcos** [comment]
Nice thanks for the persistency. Much appreciated. I’ll test tomorrow

**Comment by cabanier** [comment]
Thanks!
FYI WebVR support was removed in the latest Oculus browser so Moon Rider is currently broken.
