### ISSUE TITLE
moonrider.xyz defaults to http instead of https

### ISSUE THREAD

**Issue by MortimerGoro** [supermedium/moonrider#105]
moonrider.xyz seems to default to `http` instead of `https` if you don't type `https` manually. WebXR has SecureContext enabled which can make the site not work in VR in some browsers.

Can you default the server to https?

**Comment by dmarcos** [comment]
Thanks. It should redirect now to https. Let me know if it works for you.

**Comment by MortimerGoro** [comment]
Thanks for the quick reply!

The server is down now. I'll test when it's live again and let you know if it works.

**Comment by dmarcos** [comment]
It's working for me. Is is still down for you?

**Comment by MortimerGoro** [comment]
It's working as expected now, thanks!
