### ISSUE TITLE
Some songs don't work

### ISSUE THREAD

**Issue by JustinB4** [supermedium/moonrider#109]
Chop Shop by Twisted Insane freezes when loading and so do a few others.  I don't remember them at the moment.  You could probably search for any songs with no players on the leaderboards.  There are also others songs that do work, but you can tell that the notes are coming too slowly and then eventually the level runs out and freezes, but the music keeps going.  If you wait for it to finish, then use the Oculus button to quit, then go back into VR mode, the song will end and you can put up a high score.  This happens with a few songs, but the only I can remember is one of the 3 Rap God's by Eminem.

**Comment by ngokevin** [comment]
thanks, i'll put this top of my list. try to make it so an error won't just crash. and then actually fixing it would me be reindexing the songs.

**Comment by ngokevin** [comment]
thanks! https://github.com/supermedium/moonrider/commit/1925596ee4279cd5089c780f8f9ec4ea2d56c31a
