### ISSUE TITLE
Too many effects

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#11]
And no options to reduce / disable visual effects.. It seems to be overwhelming for some

**Comment by chrisplatorres** [comment]
I think the "broken blocks" explosion can get overwhelming when it is a supernova/ song with a lot of blocks close together, it litters the stream with shattered block parts and seems to get a little sluggish.

**Comment by ngokevin** [comment]
Simplest is perhaps speed up the animations and lower the opacity on higher modes.

Better might be to trim down the effects on large runs of notes, depending how many are active.

**Comment by ngokevin** [comment]
Play with the effects duration (particle-player) and aggressive pooling.

**Comment by ngokevin** [comment]
Sped up the effects, shrunk the Y velocity pop of missed hits.
