### ISSUE TITLE
Collision test for walls use controller 'mouse' aim

### ISSUE THREAD

**Issue by Maxmystere** [supermedium/moonrider#112]
Tested with oculus Rift S

![image](https://user-images.githubusercontent.com/24446198/81120481-195c4880-8f2d-11ea-8430-301f8ec4c4db.png)
Controller aim vector was update toward the trigger but walls still use it for wall detection

![image](https://user-images.githubusercontent.com/24446198/81120506-26793780-8f2d-11ea-8979-241c2688e1eb.png)

**Comment by ngokevin** [comment]
Thanks!

**Comment by ngokevin** [comment]
fixed
