### ISSUE TITLE
Saber angle is too forward

### ISSUE THREAD

**Issue by goatboy29** [supermedium/moonrider#114]
Recently noticed that the saber angle got tilted forward. It used to be directly in line with the handle, and now it is tilted forward 15-20 degrees. Makes it kinda awkward to slice with. 
Also, I am playing on an Oculus Quest if that makes a difference for debugging.
Thanks!

**Comment by ngokevin** [comment]
Thanks for the report! Do you see a version number in-game anywhere on the news panel? You can try clearing your browser cache if you haven't played in a while. Else it might be a real issue, although most people in Discord have seemed to been okay with it.

**Comment by goatboy29** [comment]
Yup, clearing the browser cache fixed it. Good debugging =D Thanks!
