### ISSUE TITLE
build error on node 12 and update firebase

### ISSUE THREAD

**Issue by wernert** [supermedium/moonrider#117]
Since i had a build error with node 12 similar to:
  grpc 1.19.0 no longer available #115
i have updated firebase to the latest version current: 7.19.0
and compiled with node version 12
The game is running fine on local dev server.
I have published it via github pages to https://wernert.github.io/moonrider/ for testing.
Is anything speaking against this or node 12 in general ?
Otherwise i  would like to create a pull request.

**Comment by ngokevin** [comment]
Yeah, let's switch it to Node 10

**Comment by wernert** [comment]
Is this a typo ?

> Yeah, let's switch it to Node 10

**Comment by ngokevin** [comment]
OK misread. We can set to Firebase v7.19.0.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/pull/118
