### ISSUE TITLE
Scrolling with joystick gets canceled by hover

### ISSUE THREAD

**Issue by chrisplatorres** [supermedium/moonrider#12]
While in the menu, using the joystick to scroll often gets reset by the [hover index](https://github.com/supermedium/moonrider/blob/150357fd10ec65a30e215147c1a5b8d3e46789b6/src/components/menu-controls.js#L93) as a byproduct of natural slight movements while holding the controller, which resets the scrolling since it is relative to the hover index.

**Comment by ngokevin** [comment]
I might change the joystick to just do page down / page up.

**Comment by chrisplatorres** [comment]
Yeah, that seems like the right navigation there.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/9e5c70fab29c61581eeea07ad2af4bca12cca462
