### ISSUE TITLE
Menu UI stress testing

### ISSUE THREAD

**Issue by chrisplatorres** [supermedium/moonrider#13]
For the sake of stress testing, tried as hard as I could to break things in the menu UI. 

- search query text overflows (not a realistic scenario)
- difficulty menu text gets stuck behind other menus (not sure how to repro)

![com oculus browser-20190521-164357](https://user-images.githubusercontent.com/29695350/58133214-f8e69180-7be8-11e9-9552-33816887fb80.jpg)
![com oculus vrshell-20190521-164219](https://user-images.githubusercontent.com/29695350/58133219-fa17be80-7be8-11e9-8ec1-71ba44e78d44.jpg)
![com oculus vrshell-20190521-164449](https://user-images.githubusercontent.com/29695350/58133227-fedc7280-7be8-11e9-931f-f549b33f4802.jpg)

**Comment by chrisplatorres** [comment]
Repro'd
> difficulty menu text gets stuck behind other menus (not sure how to repro)
  
Hover over song -> move joystick to right then move it back left quickly

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/9dd0b9723c4ec05ad2aff1cb2c51cd486b6a6a48

https://github.com/supermedium/moonrider/commit/28d6e4e8c69538f709d580a81297eda284a64590

Thanks!
