### ISSUE TITLE
Ray does not collide with right menu

### ISSUE THREAD

**Issue by chrisplatorres** [supermedium/moonrider#14]
The ray collides with center and left menus, but not the right menu:

![com oculus vrshell-20190521-171052](https://user-images.githubusercontent.com/29695350/58134163-8a570300-7beb-11e9-82f1-166b858c2f41.jpg)
![com oculus vrshell-20190521-171107](https://user-images.githubusercontent.com/29695350/58134164-8a570300-7beb-11e9-9e96-7bb28cb97bdd.jpg)

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/203d396597d93bb3b61c62d3e13958b3eaac8db2
