### ISSUE TITLE
Ray does not collide with song title UI in PAUSED menu

### ISSUE THREAD

**Issue by chrisplatorres** [supermedium/moonrider#15]
The ray collides with all other menu UI, but does not collide with the song title UI (cyan ray):

![com oculus vrshell-20190521-171612](https://user-images.githubusercontent.com/29695350/58134644-0dc52400-7bed-11e9-967d-b0db5184168d.jpg)

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/9ce5703e70b1e42b247c1dceb43c20bec3cbac48
