### ISSUE TITLE
Site is no longer working at all? (potentially CORS-related)

### ISSUE THREAD

**Issue by josephrocca** [supermedium/moonrider#153]
Doesn't seem to be working on Pico or on desktop as of the last couple of days? When I click on a song, it just infinitely loads. Was working fine for me a few days ago. Can anyone confirm whether or not it's working on Quest 2?

Not sure how to access dev mode on Pico to see the console there, but I'm seeing this on Desktop Chrome:

![image](https://user-images.githubusercontent.com/1167575/206260073-151c7dd8-ca05-4253-b008-1a30c0c51e0e.png)

Looks like there has been a recent update to the serving code for the songs/choreography and the CORS headers were accidentally removed?

(Weirdly there are a couple of songs that do still load for me, but those are ones that I played very recently, so I think the responses for those are cached in my browser.)

**Comment by Spideymon77** [comment]
I just tried playing it for the first time today with no luck. It's very unfortunate as people only started reporting this problem as of today. The Discord has 3 people (including me) who have reported the issue. Someone on Reddit has also reported the issue.

**Comment by josephrocca** [comment]
I'm guessing it's a fairly easy fix - hopefully no need to be too worried. Pinging @dmarcos as I think they are the person with access to the backend.

**Comment by dmarcos** [comment]
This should have been fixed already. Thanks for the patience
