### ISSUE TITLE
Ray does not collide with song title UI in loading menu 

### ISSUE THREAD

**Issue by chrisplatorres** [supermedium/moonrider#17]
similar to #14 and #15

![com oculus vrshell-20190521-173058](https://user-images.githubusercontent.com/29695350/58135025-7660d080-7bee-11e9-8daf-6743a6d4f855.jpg)

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/9ce5703e70b1e42b247c1dceb43c20bec3cbac48
