### ISSUE TITLE
Npm install doesn't work

### ISSUE THREAD

**Issue by gsp01** [supermedium/moonrider#172]
I tried to used recommended version of node (11) but it throws an error
"error while executing... git.exe ls-remote .. ngokevin/ziploader.git
host key verification failed
fatal: could not read from remote repository"

Newer node versions throw other errors. For the people who were able to build the project, which node versions were you using?

**Comment by gsp01** [comment]
I got it to work with node 11.14.0
I had to generate ssh keys, then known_host, change git config, install specific version of webpack, etc..

**Comment by fliodhais** [comment]
Hi can you share those exact details so it would be easier to replicate? I'm running into not identical but similar issues and think that this might be helpful
