### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by gsp01** [supermedium/moonrider#173]
There are no bugfixes and no new features.
Now we need Moonrider more than ever since Beat Saber is no longer gratis for Quest purchase.
I'd be happy to pay for a version with improvements.
@dmarcos @ngokevin

**Comment by dmarcos** [comment]
We recently updated to the new bsaber beatmap format and there are tons of new songs.

If you want to send some money to  https://github.com/redsolver via github spo sors it will be super appreciated.

There are no plans to add new features for now besides basic maintenance. Moonrider is free, open source and we did it for the love of it to show off how awesome WebXR is.

**Comment by gsp01** [comment]
Ok sorry for bothering, thanks for the great game!
