### ISSUE TITLE
Blocks might be too high

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#18]
It feels good to me but not the case for someone with shorter arms. It needs a bit of play testing.

**Comment by chrisplatorres** [comment]
I encountered that with a song (don't remember which one), the top blocks were at the tip of where my arm extended + lightsaber reached. The other songs were for the most part fine height wise.
  
![com oculus vrshell-20190521-164857](https://user-images.githubusercontent.com/29695350/58140059-2a6c5680-7c03-11e9-9689-7f32638a45a1.jpg)
![com oculus vrshell-20190521-164915](https://user-images.githubusercontent.com/29695350/58140060-2a6c5680-7c03-11e9-8d81-27dae0b8d66e.jpg)

**Comment by chrisplatorres** [comment]
Just loaded into moonrider again, and now every song's block height is extremely high, unreachable even though the menus are at the correct height.

**Comment by dmarcos** [comment]
It will help if you can share song / difficulty level

**Comment by chrisplatorres** [comment]
search query "Ol" and the Ol Town Road songs at the default level.

**Comment by ngokevin** [comment]
Yeah, heard about this issue too.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/34d56b34a1fc946be91bc88c8d767266e1136565#diff-bf6d982082dad2e079c7c42fd7b3a159L52

Was doing localToWorld on the same vector over and over, causing weird numbers.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/66aaca81eb8bfad85c1f45cb2784f20c172fd90c
