### ISSUE TITLE
Some beatmaps throw exception causing game to go weird state

### ISSUE THREAD

**Issue by kenshin171** [supermedium/moonrider#182]
Some of the newer beatmaps will throw an exception below. After which the same will be in a weird state where the loading beatmap screen will be stuck there

```
build.js?v=3:16 Uncaught TypeError: Cannot read properties of undefined (reading 'sort')
    at i.processBeats (build.js?v=3:16:8332)
    at i.update (build.js?v=3:16:8071)
    at i.callUpdateHandler (component.js:419:10)
    at i.updateProperties (component.js:300:12)
    at HTMLElement.value (a-entity.js:490:19)
    at HTMLElement.value (a-scene.js:722:43)
    at HTMLElement.<anonymous> (a-entity.js:727:14)
    at HTMLElement.value (a-scene.js:553:40)
    at i.onStateUpdate (build.js?v=3:343:55320)
    at AFRAME.registerSystem.dispatch (build.js?v=3:343:52193)
    ```

**Comment by moocow1452** [comment]
Seen this with the Pizza Tower OST. Thought it had something to do with the artist being "Mr. Sauceman" and the "." was throwing something for a loop.

**Comment by unsupervisednn** [comment]
I opened a PR to show a user error message instead of crashing.

You can see my version at https://unsupervisednn.github.io/moonrider

**Comment by kenshin171** [comment]
ah so its a beatmap version incompatability issue. Sad, moonrider not supporting version3 beatmaps is quite a waste. Moonrider is one of the better rythm slashing games out there even compared to native games like multrix or beatLabs.

**Comment by kenshin171** [comment]
> I opened a PR to show a user error message instead of crashing.
> 
> You can see my version at https://unsupervisednn.github.io/moonrider

somehow when i try, the sound when i slash the notes seems either lag or sppear at all. seems different from the original moonrider.xyz.

**Comment by frabul** [comment]
This pull request should solve the problem https://github.com/supermedium/moonrider/pull/200

**Comment by moocow1452** [comment]
It looks like the latest version on the website solves this issue.

**Comment by kenshin171** [comment]
yes seems like its fixed as mention below, i will jus close this issue then

> This pull request should solve the problem #200
