### ISSUE TITLE
npm install fails while installing three.js.git ( checksum error )

### ISSUE THREAD

**Issue by frabul** [supermedium/moonrider#189]
I checkd out master branch then ran npm install. 
At some point npm complains about a checksum integrity che for three.js

```
npm ERR! Verification failed while extracting three@git+ssh://git@github.com/supermedium/three.js.git#5ef2887ab3621cae54fa129a500424d6caa25b62:
npm ERR! Verification failed while extracting three@git+ssh://git@github.com/supermedium/three.js.git#5ef2887ab3621cae54fa129a500424d6caa25b62:
npm ERR! sha512-I3qUdpDBTltVg6YXEZQeckf6GCq8u/6elelab9kfHzkloUzb9aexZyNVyselBejvSmqxq70VIJksRQgxGoeJ1Q== integrity checksum failed when using sha512: wanted sha512-I3qUdpDBTltVg6YXEZQeckf6GCq8u/6elelab9kfHzkloUzb9aexZyNVyselBejvSmqxq70VIJksRQgxGoeJ1Q== but got sha512-DqIiu7ihy94n/Ediro/hchedbNbFhvYpb31ZPXlKbmTN3fo7tnICW3l4u4PA5vx2ySiTTpT2YmtNTox/Z8HB8A==. (3410328 bytes)
```

**Comment by dmarcos** [comment]
should be innocuous. we can probably remove that dependency. moonrider uses A-Frame from `vendor` or CDN.

**Comment by frabul** [comment]
To make it work i also removed dependecies to UglifyJS2, they seems to cause troubles
![image](https://github.com/supermedium/moonrider/assets/180771/a8d3dae9-757d-46ed-8902-e9e39202e805)

**Comment by dmarcos** [comment]
It seems you're in a network where you don't have access to github

**Comment by frabul** [comment]
Nope, for some reason it doesn't work only for that repo, i also tried to execute git ls-remote on that repo and it fails.
However after solvig these issues everything seems to work allright, i'm closing this. 
Thanks.
