### ISSUE TITLE
Show `Safari mobile version coming soon` message

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#22]
It looks broken in iOS at the moment.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/c5c2e4f6c1703d4e190db1d133e54e0e6fd6a2c6

**Comment by dmarcos** [comment]
This one does not seem to be working

**Comment by dmarcos** [comment]
Close in favor of https://github.com/supermedium/moonrider/issues/32
