### ISSUE TITLE
Dependency Need for Oculus Go + 1 little controller

### ISSUE THREAD

**Issue by lepidopterane-atsmith** [supermedium/moonrider#25]
I'm already a fan of Moon Rider and really love this project. However, my only headset is an Oculus Go and there are no modes where I can slash to the beat and get points with my little controller. I know Soundboxing adapts to this by having the current punching mode with only a single color, and if there's some way Moon Rider could have a mode like that, then I could finally play along.

**Comment by ngokevin** [comment]
We can perhaps do this if there's demand. It's not too hard.

**Comment by ngokevin** [comment]
Work in progress: https://github.com/supermedium/moonrider/tree/oculusgo

**Comment by ngokevin** [comment]
Away from my Rift / Vive right now, but tested on Go. https://github.com/supermedium/moonrider/pull/35

**Comment by chrisplatorres** [comment]
I think was closed by #35

**Comment by ngokevin** [comment]
Just deployed.
