### ISSUE TITLE
Louder cut noise

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#29]
https://www.reddit.com/r/OculusQuest/comments/br2r58/free_webvr_game_to_play_inbrowser_httpmoonriderxyz/eoh8w9h/?utm_source=share&utm_medium=ios_app

**Comment by feiss** [comment]
It depends a lot on the song.. I've tried songs that are quieter and the cut noise feels too strong.. :/  But yeah, with hardcore k-pop they are barely audible..

**Comment by ngokevin** [comment]
I can maybe calculate the average volume of song and adjust

**Comment by chrisplatorres** [comment]
> I can maybe calculate the average volume of song and adjust
  
It looks like there is an `enableVolume` in `aframe-audioanalyser-component` to get [average volume](https://github.com/supermedium/superframe/blob/75ba57d895ad8389ef71a108df9e943c5e7e48af/components/audioanalyser/index.js#L81-L88).

-------------------------------

Wrote this before I saw the above.. could calculate the [RMS value](https://en.wikipedia.org/wiki/Root_mean_square) :
```js
var rms = Math.sqrt(sum / (_buffer.length / 2));
```

**Comment by ngokevin** [comment]
WIP for dynamic volume: https://github.com/supermedium/moonrider/tree/autovolume

**Comment by maxim-sheronov** [comment]
Hi there! Are there some news about this feature? Really want some louder (more sensitive) cut sound. It should improve game feel.

**Comment by ngokevin** [comment]
Made it louder for now
