### ISSUE TITLE
Frame drops with lot of beats

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#30]

**Comment by ngokevin** [comment]
Can have a block merging system.

Generator spawns two notes: one into the merged geometry, and one to display at warmup + hit time.

The latter is toggled visible off when appropriate (after warmup rotation, and when it's ready to be hit). When it's toggled off, the one that's part of the merged geometry is shown.

Can reduce at times, 80 draw calls to ~25 to 30.

**Comment by ngokevin** [comment]
Reduced effects duration, removed shadows, decreased beat forward time, improved beat generation performance.
