### ISSUE TITLE
Add help text about pausing.

### ISSUE THREAD

**Issue by jacobrossi** [supermedium/moonrider#33]
Need a way to pause a song and bring up the menu while in WebVR. Suggest wiring up the B button for this.

**Comment by ngokevin** [comment]
Will do. Curious, Does a touchpad click work at the moment?

**Comment by dmarcos** [comment]
We have it hooked up to a thumbstick press now? it's not working for you?

**Comment by ngokevin** [comment]
For consideration, as long as people don't accidentally press it while playing. https://github.com/supermedium/moonrider/pull/34

**Comment by dmarcos** [comment]
Yep, dumbstick felt always to me harder to press accidentally but I understand is not very disoverable. Ideally we would use the menu button but it’s captured by the Oculus Browser taking you out of VR mode.

**Comment by dmarcos** [comment]
@jacobrossi In case you're involved with Oculus Browser. it would be good to consider leaving the menu button to content after entering VR and use Oculus button to exit like native apps.

**Comment by chrisplatorres** [comment]
I found the thumb sticks to be a good placement to bring up the menu, maybe there should be a controller keybinding infographic in the rightside / explanation UI?

**Comment by ngokevin** [comment]
Is the `b` button possible to accidentally press? https://github.com/supermedium/moonrider/pull/34

**Comment by dmarcos** [comment]
Yeah. It's where my thumb usually rest while playing.

**Comment by ngokevin** [comment]
added help text
