### ISSUE TITLE
Firefox Reality on Quest stops rendering new frames when wall approaches

### ISSUE THREAD

**Issue by DHNishi** [supermedium/moonrider#36]
I sideloaded the FF Reality for OculusVr bleeding-edge from https://fxr.glitch.me/oculusvr and tried to play Moonrider.

It runs significantly better than Oculus Browser until a wall approaches the player. The frames stop rendering until I go back to the Oculus Home and back into the app.

**Comment by DHNishi** [comment]
Logcat output from around when it dies:

05-23 20:21:33.062   710 15692 I [CT]    : AdHocPatch: [Right] t = 6018.176s, behavior transition: None -> AtRest at 6018.224s
05-23 20:21:33.172 18729 19847 I VrApi   : FPS=43,Prd=31ms,Tear=0,Early=0,Stale=72,VSnc=1,Lat=0,Fov=0,CPU4/GPU=4/4,2304/670MHz,OC=FF,TA=0/E0/E0,SP=N/F/F,Mem=1804MHz,Free=1000MB,PSM=0,PLS=0,Temp=39.0C/0.0C,TW=1.66ms,App=1.08ms,GD=0.00ms
05-23 20:21:33.261  2081  2163 W TimeWarp: HandleRequest: late frames: 93%, avg lateness: 8.52 msec
05-23 20:21:33.358 18729 19860 I UtilPoller: GPU Util 0.539683 / CPU Util 0.526786 (avg 0.508929)
05-23 20:21:33.494   710 19869 I [CT]    : VIPER: Status=6DoF,TRACKING,KF=71,Inl=198,Pts=118,Jit=0.7mm,Issues(Cam/min=0.0,IMU/min=0.0),Exp=(5.9ms,g=7,I=92)(5.7ms,g=5,I=99)(5.9ms,g=7,I=115)(6.3ms,g=6,I=110),Feat=0.24
05-23 20:21:34.110  2081  2163 W TimeWarp: HandleRequest: late frames: 97%, avg lateness: 8.55 msec
05-23 20:21:34.168   710 19868 I [CT]    : MANAGEMENT:CONSTELLATION: Status=GREEN,, Obj=4426790725860754971,6DOF=1,FusJit=0.0001mm,Issues(Cam/min=  0,IMU/min=0), Obj=2599807645527810631,6DOF=1,FusJit=0.0mm,Issues(Cam/min=  0,IMU/min=0)
05-23 20:21:34.173 18729 19847 I VrApi   : FPS=45,Prd=32ms,Tear=0,Early=0,Stale=73,VSnc=1,Lat=0,Fov=0,CPU4/GPU=4/4,2304/670MHz,OC=FF,TA=0/E0/E0,SP=N/F/F,Mem=1804MHz,Free=998MB,PSM=0,PLS=0,Temp=39.0C/0.0C,TW=1.60ms,App=1.04ms,GD=0.00ms
05-23 20:21:34.360 18729 19860 I UtilPoller: GPU Util 0.512527 / CPU Util 0.547826 (avg 0.508043)
05-23 20:21:34.828   710 19869 I [CT]    : Viper:Map_Manager: State: TRACKING_PERSISTENT, UUID=d123e183-2c00-4c5a-8ac2-23bb416c633e, Num. Persistent maps = 3,  Persistent maps:d123e183-2c00-4c5a-8ac2-23bb416c633e,a5111bbc-3f70-4b68-b575-58e196b2222f,6bfd736f-fd2e-4eaa-8dfb-bcc6a3c5c033,, Ser. Disabled = 00000000-0000-0000-0000-000000000000
05-23 20:21:34.974  2081  2163 W TimeWarp: HandleRequest: late frames: 92%, avg lateness: 9.10 msec
05-23 20:21:35.173 18729 19847 I VrApi   : FPS=47,Prd=31ms,Tear=0,Early=0,Stale=72,VSnc=1,Lat=0,Fov=0,CPU4/GPU=4/4,2304/670MHz,OC=FF,TA=0/E0/E0,SP=N/F/F,Mem=1804MHz,Free=998MB,PSM=0,PLS=0,Temp=39.0C/0.0C,TW=1.66ms,App=1.02ms,GD=0.00ms
05-23 20:21:35.223 18885 18902 E Web Content: [JavaScript Error: "TypeError: this.gamepad.hapticActuators[n.actuatorIndex] is undefined" {file: "https://moonrider.xyz/build/build.js" line: 247}]
05-23 20:21:35.223 18885 18902 E Web Content: pulse@https://moonrider.xyz/build/build.js:247:23034
05-23 20:21:35.223 18885 18902 E Web Content: tick@https://moonrider.xyz/build/build.js:247:144975
05-23 20:21:35.223 18885 18902 E Web Content: [176]</module.exports.throttleTick/<@https://moonrider.xyz/vendor/aframe-master.min.js:404:1813
05-23 20:21:35.223 18885 18902 E Web Content: value@https://moonrider.xyz/vendor/aframe-master.min.js:255:11226
05-23 20:21:35.223 18885 18902 E Web Content: value@https://moonrider.xyz/vendor/aframe-master.min.js:255:11760
05-23 20:21:35.223 18885 18902 E Web Content: [170]</module.exports/</<@https://moonrider.xyz/vendor/aframe-master.min.js:386:132
05-23 20:21:35.223 18885 18902 E Web Content: t@https://moonrider.xyz/vendor/aframe-master.min.js:87:3246
05-23 20:21:35.317  2081 19841 I Clocks  : SetSchedFifo( tid=19765, pri=0 ) succeeded
05-23 20:21:35.318  2081 19841 I Clocks  : SetSchedFifo( tid=19765, pri=0 ) succeeded
05-23 20:21:35.319  2081 19841 I Clocks  : SetSchedFifo( tid=2163, pri=0 ) succeeded
05-23 20:21:35.320  2081 19841 I Clocks  : SetSchedFifo( tid=19843, pri=0 ) succeeded
05-23 20:21:35.361 18729 19860 I UtilPoller: GPU Util 0.534522 / CPU Util 0.513514 (avg 0.477558)
05-23 20:21:35.476   710 15692 I [CT]    : R:Behavior:AtRest: deactivated
05-23 20:21:35.476   710 15692 I [CT]    : AdHocPatch: [Left] t = 6020.589s, behavior transition: AtRest -> None at 6020.640s

Suspecting the haptic actuator error might be causing issues?

**Comment by chrisplatorres** [comment]
Based on the error:
`TypeError: this.gamepad.hapticActuators[n.actuatorIndex]`

If it is bleeding edge it might be that gamepad haptics aren't implemented yet. 🤷‍♂ 

[MDN docs on `gamepad​.haptic​Actuators`](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/hapticActuators)

Moonrider uses the [aframe-haptics-component](https://github.com/supermedium/superframe/tree/master/components/haptics) which is where you see [`this.gamepad.hapticActuators[n.actuatorIndex]`](
https://github.com/supermedium/superframe/blob/967f58d62e3aa9c792fb30c9c826c613b6da5720/components/haptics/index.js#L54), it checks for `!this.gamepad.hapticActuators` so it looks like there is `hapticActuators`, but the index is undefined.

**Comment by ngokevin** [comment]
Thanks ill patch the component soon

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/ef77568f0adc68439c8aa6bafef815784cb40aad
