### ISSUE TITLE
Difficulty selection menu text gets stuck behind other menus

### ISSUE THREAD

**Issue by ltchris** [supermedium/moonrider#39]
Was mentioned in #13 , but may have gotten missed.

>  difficulty menu text gets stuck behind other menus 
Hover over song -> trigger click -> then move joystick left quickly
  
![com oculus vrshell-20190524-173213](https://user-images.githubusercontent.com/29695350/58359801-e79cbf80-7e4a-11e9-8a54-60b402534510.jpg)
![com oculus vrshell-20190521-164219](https://user-images.githubusercontent.com/29695350/58133219-fa17be80-7be8-11e9-8ec1-71ba44e78d44.jpg)

**Comment by ngokevin** [comment]
going to close old issues for now, can reopen if it's reproduced again
