### ISSUE TITLE
Ray interaction design choices

### ISSUE THREAD

**Issue by ltchris** [supermedium/moonrider#40]
This may be more of a design choice of "what should rays interact with", I noticed a few cases that might be worth interacting with:
- floor
- high score menu UI
- grade letter 3d model

![com oculus vrshell-20190524-173051](https://user-images.githubusercontent.com/29695350/58359854-2599e380-7e4b-11e9-8d61-5e5d2fe776cf.jpg)
![com oculus vrshell-20190524-173029](https://user-images.githubusercontent.com/29695350/58359855-26327a00-7e4b-11e9-89ab-d0f4e48ceef5.jpg)
![com oculus vrshell-20190524-173009](https://user-images.githubusercontent.com/29695350/58359856-26327a00-7e4b-11e9-99aa-a9f574399919.jpg)

**Comment by ngokevin** [comment]
just add `raycastable` html attribute to things want to intersect

**Comment by antoined73** [comment]
What type of interactions you would like to see ?

**Comment by antoined73** [comment]
I corrected it on the letter and leaderboard. But I didn't achieved to do it on the ground.
Adding `raycastable` to the curve object blocks the ray at some points but it stays mainly un-raycastable..
Any ideas ?

PS: I also liked to know, How can I commit and make a merge request ? I have to fork this repo first right ? It seems that I can't push directly to this repo. Thanks !

**Comment by ngokevin** [comment]
I pushed it for you, thanks!
