### ISSUE TITLE
Better quest performance

### ISSUE THREAD

**Issue by nrgapple** [supermedium/moonrider#44]
Moonrider is so close to running perfectly on the quest. 
Find ways to bring the frame rate up above 40 fps

**Comment by ngokevin** [comment]
I made some performance improvements, let me know if that visibly improved things, or not.

**Comment by PabloRomanH** [comment]
Is there any way of showing the FPS? That would help to compare.

**Comment by ngokevin** [comment]
You'd have to connect Quest, install ADB, enable developer mode, and use `chrome://inspect`. Or other Oculus tools. You can also open browser developer tools and use the Performance Tab to test FPS on a PC.

Was seeing if anyone felt it was running slowly, whether they feel it runs more smoothly now.

**Comment by chrisplatorres** [comment]
@PabloRomanH 

To add to the above^, how to wirelessly do dev tools:

**Quest plugged in**
- `adb shell ip route `
ip address is `src`

- `adb tcpip 5555`
**Quest unplugged**
- `adb connect ip:5555`

- in chrome `chrome://inspect`
- open site in quest

this worked on linux, windows was having some firewall issues:
`An attempt was made to access a socket in a way forbidden by its access permissions. (10013)`

**Comment by ngokevin** [comment]
Made lot of perf improvements including:

- Tightened up and reduced number of notes for collision checks.
- Heuristics for skipping collision checks.
- Removal of unused old code / operations, including audioanalyser stuff, updateMatrixWorlds
- When hitting or missing, move the text / state update to next frame.
- Bump A-Frame to remove raycaster setTimeout line update which not used.
- Preinitialize render-order component so component doesn't need to initialize on each pooled beat initially
- For wall raycasting, alternate left/right hand checks.
- Speed up beat generation by skipping setAttribute.
