### ISSUE TITLE
Punch score depend on velocity of punch

### ISSUE THREAD

**Issue by nrgapple** [supermedium/moonrider#47]
There is a comment in beat.js about possibly adding punch velocity to the score for punching

**Comment by ngokevin** [comment]
Yeah, it does already! Was thinking before about direction of punch, but speed is currently factored in. You get half points for hitting it, and the other half fulfilled if reach a certain speed, and scaled down if lowered than that.

**Comment by nrgapple** [comment]
Yeah I saw that later reading through the commits. Super cool
