### ISSUE TITLE
"Unable to get Node version!" during preinstall script

### ISSUE THREAD

**Issue by kaisparkle** [supermedium/moonrider#52]
Attempting to run `npm install` with Node 11.15.  https://pastebin.com/dbxnHUcw

**Comment by ngokevin** [comment]
Try removing the line in package.json, I'll get rid of it and just put the Node version in the README for now.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/500af4f81c4900dc4ca80ee74e3fd623e5d9057a

**Comment by kaisparkle** [comment]
Cheers, I had removed it but wasn't sure whether I was just doing something wrong. :)
