### ISSUE TITLE
Beats out of sync

### ISSUE THREAD

**Issue by dmarcos** [supermedium/moonrider#57]
Some users reported that there’s a small discrepancy noticeable in some songs. It could be the mapping, game logic or both.

**Comment by chrisplatorres** [comment]
Would it be due to general lag?

**Comment by antoined73** [comment]
I agree, tested it today on Oculus Quest and bloks were late

**Comment by Miaourt** [comment]
On the Quest, using Oculus's webbrowser (since Firefox's seem to be only for the Go right now) and I can agree that on the Muse's song (one of the popular ones that got listed on top) blocks are slightly lates in sync with the music

**Comment by ngokevin** [comment]
Thanks, I'll check it out after I finish color palettes. How late would you say?

**Comment by Miaourt** [comment]
I think it only affect punch mode, but maybe it's not a calibration issue with the beatmaps, but with the player's position
I feel like the player is quite behind the "hit zone" and I have to stretch my arms quite a bit to reach the targets :3 maybe make me feel like the map is out of sync I guess....

**Comment by ngokevin** [comment]
That makes sense! We did not adjust the loss of arm length for punch mode when aligning the beats.

**Comment by Miaourt** [comment]
While you're at it, I think it might be nice to make the target more easy to punch / forget a bit more the player for being a little bit out of it
Like maybe a bit more large hitbox without increasing model size o:

But maybe after re-syncing the maps it will be already more easy and don't need this tweak :)

**Comment by ngokevin** [comment]
Yeah, we could increase the bounding box a bit. It's currently at 110% the model size.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/938d55c65d8550a78afdffccdf442bf4af0c299c

I will file another to explore punch bbox. Thanks!
