### ISSUE TITLE
Sabers only 'slice' at the tip, casting audio issue - Quest

### ISSUE THREAD

**Issue by owlthathurts** [supermedium/moonrider#59]
Just tried it for the first time on the Quest. Kudos to your fine efforts, keep improving! Unfortunately, I already own Beat Saber. No biggie though :P

The main issues I had with MR were that the sabers only seemed to slice the arrow at the very tip, the only way I could get a decent score was to impale beats instead of rhythmically slicing. This way, it is not in synch with the music(all songs). 

Other than that, when I cast to my Shield or Chromecast, both played video fine, but the only sound that came out was what I can best describe was a 'windy static'. 

Minor gripe: those muted colors could be a little richer for a more exciting theme(I haven't read the color-blind discussions though, if that's why the color choice).

Again, cheers! So impressed by you guys!

**Comment by ngokevin** [comment]
Thanks! We can maybe expand the bounding box a bit, and yeah we will add color options once we free up.

**Comment by kaisparkle** [comment]
From what I can feel, it seems like the handles don't count as a hit, whereas in Beat Saber it feels like they do.

**Comment by ngokevin** [comment]
Extended the bounding box a bit more: https://github.com/supermedium/moonrider/commit/336f1c5c1ccc7081cdbd1ff8ecfbc41cfb58ee61 ... if it's still not feeling good, maybe a raycaster provides more precision.

**Comment by ngokevin** [comment]
Let me know if it's still an issue and you still need to impale arrows or can't hit with the handle. I'm not sure we can fix the Shield / Chromecast issue, that might be due to Oculus Browser.

**Comment by owlthathurts** [comment]
First off... YOU GUYS ADDED A BLAZERS COLOR THEME. I'm in Portland, so.. holy shit, you did that lol

It really does feel different now, for the better. K actually made it through a song 😋 Playing BS and MR back to back though, I think the main thing I notice different in the play is that the arrows are considerably smaller than the blocks in BS, making it more of an effort to hit them dead center. And with that, the sabers feels smaller making it even harder and more 'serious' in comparison. Also, the high arrows seem really high, whereas in BS, all blocks seem a bit low(no matter the orientation setting).

I'd soon forget BS if they both felt the same TBH. The songs are a perfect variety in MR 👍👍

**Comment by ngokevin** [comment]
Thanks! We’ll keep trying to play with sizes and heights then. Maybe lower a bit. We did increase them very large, and making them larger has to make the top beats even higher. Go Blazers.

**Comment by chris542** [comment]
Hey devs,. Thanks for an amazing open source experience!! I refunded my beatsaber because i was too lazy putting custom songs on. With MR i can casually play any song! 

Just wanted to point out that hitting with saber is still only counted as hit only at the tip. Its really hard to hit the blocks with the timing of the music. 

Sometimes the ui goes whacky after 3-4 songs. So i need to refresh..

Also for punch mode, when you hit the block too early, it just skips through. So you cant 'punch' but just leave you fist where the block is flying to to make it hit. I hope this makes sense.

Thanks for the game though!!
