### ISSUE TITLE
Feature Request: Mark songs as Favorite

### ISSUE THREAD

**Issue by kellyluck** [supermedium/moonrider#61]
If it's possible, it would be nice to flag songs as favorites and possibly filter searches for them.

**Comment by ngokevin** [comment]
Maybe I shove it in under the Playlists section? And add a Heart button to the song detail area?

**Comment by kellyluck** [comment]
I think that would work really well, yeah.

**Comment by BenCearlock** [comment]
Would LOVE to see this implemented.

**Comment by ngokevin** [comment]
I’ll put it next on the list 😄

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/243c7a5bc827a234c5c8adfc2cf78dd77ab71daf

Click the star! Will show up in favorites playlist. Deploying soon.

![Screen Shot 2019-06-09 at 8 41 07 PM](https://user-images.githubusercontent.com/674727/59171246-f21bb200-8af6-11e9-8559-7099c366e1ed.png)

**Comment by kellyluck** [comment]
Awesome, thanks!
