### ISSUE TITLE
Pause the game when coming out of VR mode

### ISSUE THREAD

**Issue by PabloRomanH** [supermedium/moonrider#62]
If you can detect when the user switches in and out of VR mode, it would be nice for the game to pause. Sometimes I hit the menu button by accident when playing hard levels, and it would be nice for the game to pause and let me get back into VR mode without bungling the whole song.

**Comment by ngokevin** [comment]
Will do!

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/4864aff543699820198c5f0900148a332464bc0b
