### ISSUE TITLE
osu! Mode

### ISSUE THREAD

**Issue by ngokevin** [supermedium/moonrider#67]
https://osu.ppy.sh is an enduring popular rhythm game with an active community and open API, that might be interested in a VR adapation.

**Comment by Maxmystere** [comment]
There is already an adaptation : McOsu
https://store.steampowered.com/app/607260/McOsu/
https://github.com/McKay42/McOsu

**Comment by ngokevin** [comment]
Thanks. I think I may just come up with more original modes instead.
