### ISSUE TITLE
Invalidate cache for old ZIPs. / audio buffers.

### ISSUE THREAD

**Issue by ngokevin** [supermedium/moonrider#79]
I think Oculus Browser kicks out of VR when out of memory, might be due to the ZIP cache piling up.

**Comment by chrisplatorres** [comment]
Noticed this would happen after about 3 songs, also around that time beats would be less likely to break when hit.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/commit/4b9c73f1284a5105fb6cc4cac5936d807d8c0121
https://github.com/supermedium/moonrider/commit/77f077dd6002aa79fce9929a6631e7a204b92939
https://github.com/supermedium/moonrider/commit/ba88e8764839e966e2e9e04f69e8de52d3b51166
