### ISSUE TITLE
Songs & play area is missing

### ISSUE THREAD

**Issue by munrider** [supermedium/moonrider#83]
Hello,

I deployed the moonrider script on my ubuntu vps, but after clicking begin, the area where the playlist, songs and play button is missing.

![moonrider](https://user-images.githubusercontent.com/56148104/66184896-73362080-e675-11e9-9028-56e1b928cd7f.png)

What files should I edit?

Thanks.

**Comment by ajay-sreeram** [comment]
i am also facing the same problem :(

**Comment by ahmadster** [comment]
Yup, same here

**Comment by ahmadster** [comment]
Not fixed, but some progress to share.
I set `mainMenuActive` to`true` in `index.js`.
It's showing now but it seems to be broken. 

It seems that the `computeState` function is never called.

**Comment by andrejoin1991** [comment]
Same problem. I've fixed it after struggling to find the solution. You have to delete node_modules and change the version of the library "aframe-state-component". You have to set the "6.7.0" version without caret.

**Comment by ngokevin** [comment]
Thanks, I'll edit.

**Comment by ngokevin** [comment]
https://github.com/supermedium/moonrider/blob/master/package.json
