### ISSUE TITLE
[Feature propositions] daltonian version and tutorial mode

### ISSUE THREAD

**Issue by TheZeldaBoss** [supermedium/moonrider#85]
Hi,

I've just tried MoonRider on an Oculus Quest, it works really great, we just have to understand that we need to click the VR headset on bottom right of the page (it's not obvious, why not adding a text on it ?)
I've played it with a daltonian person which didn't see the colors of elements (pink and blue), would it be possible for you to add a daltonian version of the game, with distinct shades of grey for the different elements ? What could be great too would be a small tutorial for people playing the game for the first time.

**Comment by dmarcos** [comment]
FYI, There's a `themes` button at the bottom of the main menu to change the color schema

**Comment by ngokevin** [comment]
Thanks for the feedback! Will try to add text to the VR button.

**Comment by ngokevin** [comment]
There's text now + different color schemes. Don't think we'll have time for a tutorial mode
