### ISSUE TITLE
Someone ripping you off? beatsaber.io

### ISSUE THREAD

**Issue by andrewmk** [supermedium/moonrider#86]
A copy has appeared at beatsaber.io with the title changed. I'm assuming this isn't 'official'?

**Comment by UshudaKnow** [comment]
LOL. You're a fucking idiot.
This is a free open source project on github, which mean anyone can use for their own projects.
Why do you think developers to whom you're whining upload their source code in the first place?
You're a fucking joke lol

**Comment by feiss** [comment]
UshudaKnow I think your comment is completely out of place, you should take it back. Nothing you answered really makes sense regarding andrewmk's question. I think he knows the meaning of open source perfectly, he was just informing of the existence of that website and asking if it was official or not. And that is a completely valid and pertinent question, no matter the license of this project.

**Comment by ngokevin** [comment]
Yes, while you are correct Ushuda, let's keep it civil! Anyone is free to re-host.
