### ISSUE TITLE
 the game stops after hit [oculus go]

### ISSUE THREAD

**Issue by alexander-shvets** [supermedium/moonrider#87]
In Classic Mode

**Comment by DannyFGitHub** [comment]
According to chrome dev tools the exception hit occurs as you hit a node on the Go. It calls the haptics_beat.pulse() method. 

pulse: function (force, dur) {
    var actuator;
    var data = this.data;
    if (!data.enabled || !this.gamepad || !this.gamepad.hapticActuators) { return; }
    actuator = this.gamepad.hapticActuators[data.actuatorIndex];
    actuator.pulse(force || data.force, dur || data.dur);
  },

Which the module hits uncaught exception on:
actuator.pulse(force || data.force, dur || data.dur);

Seen as the module is read-only... quickest workaround for me was to comment out the haptic pulse method call:
weaponEl.components.haptics__beat.pulse();

After commenting it out I was able to play a song successfully.

**Comment by ngokevin** [comment]
Should be fixed now
