### ISSUE TITLE
Make height adjustments for the notes

### ISSUE THREAD

**Issue by Oliv6176** [supermedium/moonrider#96]
Hey :-)
It would be nice if it was possible to adjust the height of the notes, because I find them quite low (I’m 2 meters tall) and get some back pains after a few minutes :-/
Greetings Oliver G.

**Comment by ngokevin** [comment]
thanks, i'll look into moonrider improvements after i finish my current work!

**Comment by ngokevin** [comment]
@Oliv6176 @l3d00m height now adjusts to your height
