### ISSUE TITLE
Moonrider broken on the Quest after latest firmware update

### ISSUE THREAD

**Issue by vedtam** [supermedium/moonrider#98]
Hi guys,

After the latest update on the Quest (v. 14) the game starts without controllers, no way to press the start button:

![89119428_10160935620154815_7234102206511710208_o](https://user-images.githubusercontent.com/4981592/75667428-55023a00-5c80-11ea-8817-cc04c22785c5.jpg)

Tried to press the start button before entering immersive mode, which starts the game, but the controllers (fists/sword) are offset, they have the original orientation of the controller (like a gun) instead of like when holding a sword in hand.

Anyone else noticed this issue?
Thanks!

**Comment by dmarcos** [comment]
On the Oculus Browser?

**Comment by ngokevin** [comment]
I just tried on v14 and it works okay for me. Can you try restarting the Quest maybe?

**Comment by dmarcos** [comment]
Can you run any other WebVR content like this example: https://aframe.io/aframe/examples/showcase/anime-UI/

**Comment by vedtam** [comment]
Hi,

Yes on the Oculus browser, here's a demo video: https://streamable.com/1cfco

I can see some strange clipping too, I mean, the aurora on the left and right get cut as I look at it and some similar clipping / missing assets in the distance (there was a glowing sun like thing at the end of the runway?)

The second example seems ok, however as I move my head, some clipping (or antialiasing) seems to happen on the ceiling (but not sure if that's an actual issue):

![88198463_10160940354109815_3190042772480458752_o](https://user-images.githubusercontent.com/4981592/75746249-66038780-5d22-11ea-8fe9-2859173b1017.jpg)

**Comment by dmarcos** [comment]
What Browser version are you in? See browser menu `About Oculus Browser`

**Comment by dmarcos** [comment]
Can you also try clearing the browser cache?

**Comment by vedtam** [comment]
Cleared the cache and restarted the headset, same happens. Browser version:

![Screen Shot 2020-03-03 at 07 46 15](https://user-images.githubusercontent.com/4981592/75746511-27ba9800-5d23-11ea-9532-1b0c73595e63.png)

**Comment by vedtam** [comment]
Are you having this update, no issues so far?

**Comment by dmarcos** [comment]
No. We cannot reproduce the issue on any of our devices. Make sure you're not running anything in the background: Any sideloaded apps via sidequest? Is your headset connected to a computer via link?

@Artyom17 Any insights on what it might be happening?

**Comment by kwadroke** [comment]
I just saw this issue after upgrading the Oculus Browser about 15 minutes ago. I tried Moonrider before upgrading. While the controllers and the swords were pointing about 15-20 degrees (guess-timate) off they were showing up. After the upgrade they were no longer there.

**Comment by dmarcos** [comment]
What browser version?

**Comment by kwadroke** [comment]
Oculus Browser 79.0.3945.126

**Comment by dmarcos** [comment]
That's Chromium version. See [comment above](https://github.com/supermedium/moonrider/issues/98#issuecomment-593779415)

**Comment by kwadroke** [comment]
Right. Sorry. Too used to doing it the desktop way.
Version 8.2.1.201077605

May help as well:
https://support.oculus.com/1832320770186303
https://developer.oculus.com/documentation/oculus-browser/browser-release-notes/

**Comment by vedtam** [comment]
@dmarcos using no link, sideloded app only 1-2 but I don't thing these could interfere with chromium in any way.
I could try to remote debug the oculus browser but I don't think if it exposes the same api as chrome desktop / mobile does.

**Comment by dmarcos** [comment]
It’s easy to debug: https://developer.oculus.com/documentation/oculus-browser/browser-remote-debugging/?locale=en_US

You can use Chrome dev tools. Any console errors / messages would be very useful

**Comment by vedtam** [comment]
Oh cool, then will do some debugging as I have a break and will be back with the results.

**Comment by vedtam** [comment]
Back with the results. Started with a fresh cache, cleared everything with the window reloaded:

<img width="1440" alt="Screen Shot 2020-03-04 at 4 43 18 PM" src="https://user-images.githubusercontent.com/4981592/75890970-c9cba480-5e37-11ea-995f-53d9d70eaccc.png">

and further down:

<img width="670" alt="Screen Shot 2020-03-04 at 4 44 53 PM" src="https://user-images.githubusercontent.com/4981592/75891139-07303200-5e38-11ea-9cae-876fc1fbc15e.png">

Full log:
[moonrider.xyz-1583332771281.log](https://github.com/supermedium/moonrider/files/4287898/moonrider.xyz-1583332771281.log)

No other tab open (hopefully the debugger display doesn't count).

**Comment by dmarcos** [comment]
Thanks. I don’t see anything revealing

**Comment by vedtam** [comment]
But I guess it has to do with: "WebXR is already in use". Will set a few brake points to see if something comes up.

**Comment by dmarcos** [comment]
Your experience is entering VR. Problem is that the controllers don’t show up, right? Also try rebooting your headset

**Comment by vedtam** [comment]
I think there's more to it. Regarding the controllers, I can "force" start the game while the session is inlined by clicking the begin button and entering VR after that, the controllers will show up but the orientation is wrong.

What's more, the far clipping plane has issues as well, I mean when I look up to the aurora it dissapears partially and the "sun/start" isn't showing at all in the distance just a pitch black background.

**Comment by Sn00pDoug** [comment]
Hey all. I replicated this bug on my Quest, but it only happens when using the secure connection https:\\moonrider.xyz.  When I use the unencrypted http:\\moonrider.xyz, the controllers are visible.  Hope this helps!

**Comment by ngokevin** [comment]
I've reverted the A-Frame upgrade patch. for now. Thanks all for investigating!

**Comment by Artyom17** [comment]
Sorry guys, totally missed this thread. @cabanier wanted to investigate this issue. Rik, do you have it repro-ed?

to @Sn00pDoug : when you use http then the experience runs in WebVR mode. WebXR supports https only.

**Comment by cabanier** [comment]
I wasn't able to determine the issue. 
Exiting the session and starting it again brings back the controllers. They are slightly offset from before but I believe that is expected behavior since three.js changed it for WebXR.

Maybe someone who has better knowledge of aframe can figure this out quicker than me. If no, I can investigate.

**Comment by cabanier** [comment]
@ngokevin @dmarcos I investigated this a bit more.
It seems that there's a problem with aframe.

`updateControllerList` fires an event to signal that something changed with the controllers. When starting a WebXR session, `updateController` in the `tracked-controls-webxr`module is called before the `onControllersUpdate` in `oculus-touch-controls`. Because of this, the first time you run, the hand-ness of the controller is not populated and the system assumes that there are no controllers.

What's the cleanest way to resolve this?

**Comment by dmarcos** [comment]
Thanks. It’s weird that handedness is not populated. Is that the browser expected behavior or a bug?

**Comment by cabanier** [comment]
> Thanks. It’s weird that handedness is not populated. Is that the browser expected behavior or a bug?

I think it' a bug in aframe. I'm unsure why it is working correctly for the samples but not moon rider. I can investigate if you want.

**Comment by dmarcos** [comment]
Thanks. It would be interesting to see a barebones A-Frame example to reproduce the issue. Just to understand and make sure we're fixing the real bug and not only the symptoms.

**Comment by cabanier** [comment]
ok! I will take a look

**Comment by dmarcos** [comment]
Thanks

**Comment by cabanier** [comment]
@dmarcos I don't see a lot of differences. Moonrider seems to create a raycaster earlier. Could that trigger an early call to `updateController'?

**Comment by dmarcos** [comment]
Maybe somehow moonrider is missing the `controllersupdated` event. Worth checking if the event is [emitted at all](https://github.com/aframevr/aframe/blob/master/src/systems/tracked-controls-webxr.js#L46) on Quest + moonrider and if it does it might fire early and missed here?

https://github.com/aframevr/aframe/blob/master/src/components/tracked-controls-webxr.js#L40

**Comment by cabanier** [comment]
It's possible that https://github.com/mrdoob/three.js/pull/18639 will fix this. 
@dmarcos how do I include a custom version of three.js in the aframe build?

**Comment by cabanier** [comment]
> Maybe somehow moonrider is missing the `controllersupdated` event. Worth checking if the event is [emitted at all](https://github.com/aframevr/aframe/blob/master/src/systems/tracked-controls-webxr.js#L46) on Quest + moonrider and if it does it might fire early and missed here?

That event is called, but earlier than on the aframe examples (ie In-Vr performance)

**Comment by dmarcos** [comment]
I don't think that will help. A-Frame doesn't rely on the `inputsourceschange` event and queries manually inputSources checking for changes. Also [A-Frame examples](https://aframe.io/aframe/examples/showcase/tracked-controls/) work as expected AFAIK  I suspect is something specific to Moonrider. It could also be, but less likely a bug on A-Frame that Moonrider is revealing.

**Comment by dmarcos** [comment]
It's worth investigating if `controllersupdated` event is properly fired on a-scene when moonrider loads and the controllers don't show up. 
```
  sceneEl.addEventListener('controllersupdated', function () { console.log("CONTROLLERS UPDATED EMITTED) });
```

**Comment by dmarcos** [comment]
> 
> 
> > Maybe somehow moonrider is missing the `controllersupdated` event. Worth checking if the event is [emitted at all](https://github.com/aframevr/aframe/blob/master/src/systems/tracked-controls-webxr.js#L46) on Quest + moonrider and if it does it might fire early and missed here?
> 
> That event is called, but earlier than on the aframe examples (ie In-Vr performance)

Thanks for investigating. Much appreciated. It might be that the  `controllersupdated` event is emitted before the [moonrider controllers are initialized and ready to go](https://github.com/supermedium/moonrider/blob/master/src/scene.html#L160) . That also explains why forcing the controllers update on initialization in your [PR](https://github.com/aframevr/aframe/pull/4522/files) fixes the issue.

**Comment by cabanier** [comment]
> It's worth investigating if `controllersupdated` event is properly fired on a-scene when moonrider loads and the controllers don't show up.
> 
> ```
>   sceneEl.addEventListener('controllersupdated', function () { console.log("CONTROLLERS UPDATED EMITTED) });
> ```

I just added it and the event is called

**Comment by cabanier** [comment]
> Thanks for investigating. Much appreciated. It might be that the `controllersupdated` event is emitted before the [moonrider controllers are initialized and ready to go](https://github.com/supermedium/moonrider/blob/master/src/scene.html#L160) . That also explains why forcing the controllers update on initialization in your [PR](https://github.com/aframevr/aframe/pull/4522/files) fixes the issue.

So is my fix correct, or is it just working around an underlying issue?

**Comment by dmarcos** [comment]
> 
> 
> > Thanks for investigating. Much appreciated. It might be that the `controllersupdated` event is emitted before the [moonrider controllers are initialized and ready to go](https://github.com/supermedium/moonrider/blob/master/src/scene.html#L160) . That also explains why forcing the controllers update on initialization in your [PR](https://github.com/aframevr/aframe/pull/4522/files) fixes the issue.
> 
> So is my fix correct, or is it just working around an underlying issue?

Thinking about. Moonrider controller setup should be synchronous. I think there's some issue there. On the other hand your fix might make A-Frame controllers setup resilient to a asynchrony.

**Comment by cabanier** [comment]
> Thinking about. Moonrider controller setup should be synchronous. I think there's some issue there. On the other hand your fix might make A-Frame controllers setup resilient to a asynchrony.

Let me know if there's anything I can do to help.
