### ISSUE TITLE
Moonrider freezes at startup (both https and http) on Oculus browser

### ISSUE THREAD

**Issue by cutterjunk** [supermedium/moonrider#99]
I am a daily user, and 3 days ago both http://moonrider.xyz/ and https:moonrider.xyz/ freeze immediately on opening.

The begin button appears, but the road does not. Only a star below me is shown. The button does not have a hover-over effect. 

Important:
When I go to another browser (firefox), AND when I go to private mode within oculus browser, there is no freezing. 

I believe the trouble began after I changed to a specific theme, but it may have been coincidence. Took me many hours to create the daily playlist, so a fix would be great.

**Comment by dmarcos** [comment]
reset the browser cache.  Keep only the "Cached images and files" checkbox selected and the rest unselected if you want to preserve your favorites list.

**Comment by dmarcos** [comment]
Closing this. We can reopen if 'resetting the cache' doesn't solve the issue
